# Flowbite plugin requires tailwindcss but doesn't declare it.
# This patch allows it to work under Yarn PnP strict mode.
packageExtensions:
  flowbite@*:
    dependencies:
      tailwindcss: "*"
# plugins
plugins:
  - checksum: ffd9b2dbbe2efe008987559cb4cfb8feeee45eae9b550bbd6154a535919362466f4a09a9de56f1e1502a804592b95848839bc9c5bdd7d4e2891d8532e7045258
    path: .yarn/plugins/@yarnpkg/plugin-licenses.cjs
    spec: "https://raw.githubusercontent.com/mhassan1/yarn-plugin-licenses/v0.15.1/bundles/@yarnpkg/plugin-licenses.js"
